CREATE TABLE IF NOT EXISTS AC_Protocol 
(
    Protocol	VARCHAR(512),
    Brand	VARCHAR(512)
);

INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('AIRTON', 'Airton');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('AIRWELL', 'Airwell');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('AIWA_RC_T501', 'Aiwa');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('AMCOR', 'Amcor');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ARGO', 'Argo');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('BOSCH144', 'Bosch');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC', 'Carrier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC40', 'Carrier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC64', 'Carrier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC128', 'Carrier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC84', 'Carrier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC', 'Surrey');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC40', 'Surrey');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CARRIER_AC64', 'Surrey');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CLIMABUTLER', 'Clima-Butler');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX', 'Airwell');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX', 'Beko');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX', 'Bosch');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX', 'Kaysun');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX', 'Midea');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX', 'Toshiba');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX48', 'Airwell');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX48', 'Beko');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX48', 'Bosch');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX48', 'Kaysun');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX48', 'Midea');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('COOLIX48', 'Toshiba');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('CORONA_AC', 'Corona');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN128', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN160', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN216', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN312', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN2', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN152', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN176', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN200', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DAIKIN64', 'Daikin');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('DELONGHI_AC', 'Delonghi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ECOCLIM', 'EcoClim');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'AUX');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'Electra');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'Frigidaire');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'Subtropic');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'Centek');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'AEG');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('ELECTRA_AC', 'Electrolux');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('FUJITSU_AC', 'Fujitsu');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('FUJITSU_AC', 'Ogeneral');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GOODWEATHER', 'Goodweather');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Amana');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Cooper & Hunter');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', ' EKOKAI');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Gree');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Green');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'RusClimate');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Soleus Air');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Ultimate');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('GREE', 'Vailland');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HAIER_AC176', 'Daichi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HAIER_AC', 'Haier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HAIER_AC176', ' Mabe');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HAIER_AC_YRW02', 'Haier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HAIER_AC160', 'Haier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HAIER_AC176', 'Haier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC1', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC2', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC264', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC344', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC424', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC3', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('HITACHI_AC296', 'Hitachi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('KELON168', 'Hisense');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('KELON', 'Kelon');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('KELON168', 'Kelon');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('KELVINATOR', 'Gree');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('KELVINATOR', 'Kelvinator');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('KELVINATOR', 'Sharp');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('LG', 'General Electric');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('LG', 'LG');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('LG2', 'LG');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Comfee');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Danby');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Kaysun');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Keystone');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Lennox');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Midea');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'MrCool');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Pioneer System');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIDEA', 'Trotec');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIRAGE', 'Maxell');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIRAGE', 'Mirage');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MIRAGE', 'Tronitechnik');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI112', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI136', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI2', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI_AC', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI_HEAVY_152', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('MITSUBISHI_HEAVY_88', 'Mitsubishi');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('NEC', 'Duux');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('NEOCLIMA', 'Neoclima');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('NEOCLIMA', 'Soleus Air');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('PANASONIC_AC', 'Panasonic');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('PANASONIC_AC32', 'Panasonic');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('SAMSUNG_AC', 'Samsung');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('SANYO_AC', 'Sanyo');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('SANYO_AC152', 'Sanyo');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('SANYO_AC88', 'Sanyo');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('SHARP_AC', 'Sharp');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TCL96AC', 'Daewoo');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TCL96AC', ' Leberg');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TCL96AC', 'TCL');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TCL96AC', 'Teknopoint');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TECO', 'Alaska');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TEKNOPOINT', 'Teknopoint');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TOSHIBA_AC', 'Carrier');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TOSHIBA_AC', 'Toshiba');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TRANSCOLD', 'Transcold');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TROTEC', 'Duux');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TRUMA', 'Truma');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TROTEC', 'Trotec');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('TROTEC_3550', 'Trotec');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('VOLTAS', 'Voltas');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('VESTEL_AC', 'Vestel');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('WHIRLPOOL_AC', 'Whirlpool');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('WHYNTER', 'Whynter');
INSERT INTO AC_Protocol (Protocol, Brand) VALUES ('YORK', 'York');
